services:
  db:
    container_name: linktok-pg
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: urls
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    container_name: linktok-redis
    image: redis:latest
    hostname: localhost
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pgdata:
